FROM python:3.7-slim
WORKDIR /app
COPY . .
RUN pip3 install -r requirements.txt --no-cache-dir
RUN ls -a
RUN ls api_yamdb/ -a
CMD python3 manage.py runserver 0:5000
# CMD ["gunicorn", "api_yamdb.wsgi:application", "--bind", "0:8000" ]
