# Generated by Django 2.2.16 on 2022-04-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220406_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamdbuser',
            name='replacement_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='role',
            field=models.CharField(choices=[('user', 'пользователь'), ('admin', 'админ'), ('moderator', 'модератор')], default='user', max_length=10, verbose_name='роль'),
        ),
    ]
