# Generated by Django 2.2.16 on 2022-04-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220406_1709'),
        ('reviews', '0002_auto_20220404_2028'),
        ('reviews', '0004_auto_20220405_0048'),
    ]

    operations = [
    ]
