# Generated by Django 2.2.16 on 2022-04-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220407_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='role',
            field=models.CharField(choices=[('user', 'пользователь'), ('admin', 'админ'), ('moderator', 'модератор')], default='user', max_length=9, verbose_name='роль'),
        ),
    ]
