# Generated by Django 2.2.16 on 2022-04-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220407_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamdbuser',
            name='replacement_code',
        ),
    ]
