# Generated by Django 2.2.16 on 2022-04-07 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_remove_yamdbuser_replacement_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Допускаются буквы, цифры и знаки _ @ / + - .', regex='^[\\w.@+-]+$')], verbose_name='имя пользователя'),
        ),
    ]
